import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import AnimationCanvas from '../components/AnimationCanvas'
import { createShipCloseUp } from '../modules/animation-factory'



const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Moon Lander - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.frame}>

          <h2>About</h2>
          <p>Moon-lander is a free browser game in which you pilot a small landing craft in a variety of planetary and deep space environments. The sucessfull pilot will need to cope with different atmospheres, terrains and levels of gravity to land safely.</p>
          <p>More of my free games can be found at <a className={styles.exLink} href="http://www.davidblatcher.co.uk/">http://www.davidblatcher.co.uk/</a>.</p>

          <h3>Technical</h3>
          <p>The game uses my <a className={styles.exLink} href="https://github.com/dblatcher/worlds">physics-worlds</a> package to create the game levels. Physics-worlds is a flexible, object-orientated typescript physics engine intended for building games, simulations and animations.</p>
          <p>The source code is available at <a className={styles.exLink} href="https://github.com/dblatcher/moon-lander">https://github.com/dblatcher/moon-lander</a>.</p>

          <p>
            <Link href="/" passHref={true}><a>&lArr; homepage</a></Link>
          </p>

          <AnimationCanvas makeWorld={createShipCloseUp}
            magnify={.5}
            frameClass={styles.cornerAnimation} />

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
