import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import AnimationCanvas from '../components/AnimationCanvas'
import { createShipCloseUp } from '../modules/animation-factory'
import { asteroidField } from '../modules/asteroid-field'
import { platformGame } from '../modules/platform-game'
import { moonLander } from '../modules/moon-lander'
import GameModeList from '../components/GameModeList'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Arcade World</title>
        <meta name="description" content="Allecollection of physics-based games. Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div className={styles.frame}>

          <header>
            <h1>Arcade World</h1>
            <span className={styles["bottom-rivets"]}></span>
          </header>

          <AnimationCanvas makeWorld={createShipCloseUp}
            frameStyle={{
              border: "2px solid yellow",
              borderRadius: '50%',
              overflow: 'clip',
              textAlign: 'center',
              alignSelf: 'center',
              flexShrink: 0,
            }} />

          <GameModeList game={moonLander} />
          <GameModeList game={platformGame} />
          <GameModeList game={asteroidField} />

          <p>
            <Link href={`/about`} passHref={true}>
              <a>about this game &rArr;</a>
            </Link>
          </p>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
